/* Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.  */

#include <stdio.h>

int ft_fibonacci(int index)
{
    if (index < 0)
        return (-1);
    if (index < 2)
        return (index);
    return (ft_fibonacci(index - 2) + ft_fibonacci(index - 1));
}

int main()
{
    int sum = 0;
    for (int i = 1; i <= 33; i++)
    {
        if (ft_fibonacci(i) % 2 == 0)
            sum += ft_fibonacci(i);
    }
    printf("%d", sum);
}
